#!/bin/sh

PROGPATH='/usr/lib/nagios/plugins'
REBOOT_REQ_PKGS='/var/run/reboot-required.pkgs'

. "$PROGPATH/utils.sh"
if [ -f "$REBOOT_REQ_PKGS" ]; then
    pkg_list=$(cat "$REBOOT_REQ_PKGS" | tr -s '\n' ' ')
    echo "WARNING : Packages pending reboot: $pkg_list"
    exit $STATE_WARNING
else
    echo "OK : No pending updates requiring reboot"
    exit $STATE_OK
fi

# vim: syntax=sh ts=4 sw=4 sts=4 et sr
